AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: SAM template for Sibyl Telegram Interface

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Resources:
  SibylTelegramMessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SibylTelegramMessageQueueDLQ.Arn
        maxReceiveCount: 3

  SibylTelegramMessageQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days

  SibylTelegramFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: sibyl_telegram_interface.handlers.lambda_handler.lambda_handler
      Description: Lambda function for handling Telegram bot messages
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          SQS_QUEUE_URL: !Ref SibylTelegramMessageQueue
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sibyl/telegram/bot-token
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SibylTelegramMessageQueue.QueueName
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - https://api.telegram.org
      Tags:
        Environment: !Ref Environment
        Application: SibylTelegram

  SibylTelegramMessageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: sibyl_telegram_interface.handlers.message_processor.lambda_handler
      Description: Process Telegram messages from SQS queue
      Timeout: 60  # Longer timeout for processing
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SibylTelegramMessageQueue.Arn
            BatchSize: 1  # Process one message at a time
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sibyl/telegram/bot-token
      Tags:
        Environment: !Ref Environment
        Application: SibylTelegram

  SibylTelegramWebhookSetupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: sibyl_telegram_interface.handlers.webhook_setup.lambda_handler
      Description: Function to set up Telegram webhook
      Timeout: 60
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sibyl/telegram/bot-token
      Tags:
        Environment: !Ref Environment
        Application: SibylTelegram

  SibylTelegramWebhookSetup:
    Type: Custom::WebhookSetup
    Properties:
      ServiceToken: !GetAtt SibylTelegramWebhookSetupFunction.Arn
      FunctionUrl: !GetAtt SibylTelegramFunctionUrl.FunctionUrl

Outputs:
  FunctionUrl:
    Description: "Lambda Function URL for the webhook"
    Value: !GetAtt SibylTelegramFunctionUrl.FunctionUrl
  QueueUrl:
    Description: "URL of the SQS queue for message processing"
    Value: !Ref SibylTelegramMessageQueue
  DLQUrl:
    Description: "URL of the Dead Letter Queue"
    Value: !Ref SibylTelegramMessageQueueDLQ
