AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: SAM template for Sibyl Telegram Interface

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name
  AgentId:
    Type: String
    Default: GHYCJWTPIA
    Description: Bedrock Agent ID for Sibyl
  AgentAliasId:
    Type: String  
    Default: Z6NEJEPJPX
    Description: Bedrock Agent Alias ID for Sibyl

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        POWERTOOLS_LOG_LEVEL: "INFO"

Resources:
  WebhookHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/sibyl-telegram-${Environment}-webhook-handler
      RetentionInDays: 60

  MessageProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/sibyl-telegram-${Environment}-message-processor
      RetentionInDays: 60

  WebhookSetupLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/sibyl-telegram-${Environment}-webhook-setup
      RetentionInDays: 60

  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MessageQueueDLQ.Arn
        maxReceiveCount: 3

  MessageQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days

  WebhookHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: sibyl_telegram_interface.handlers.lambda_handler.lambda_handler
      Description: Lambda function for handling Telegram bot messages
      LoggingConfig:
        LogGroup: !Ref WebhookHandlerLogGroup
        LogFormat: Text
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          SQS_QUEUE_URL: !Ref MessageQueue
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sibyl/telegram/bot-token
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MessageQueue.QueueName
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - https://api.telegram.org
      Tags:
        Environment: !Ref Environment
        Application: SibylTelegram
    DependsOn: WebhookHandlerLogGroup

  MessageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: sibyl_telegram_interface.handlers.message_processor.lambda_handler
      Description: Process Telegram messages from SQS queue
      LoggingConfig:
        LogGroup: !Ref MessageProcessorLogGroup
        LogFormat: Text
      Timeout: 60  # Longer timeout for processing
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          AGENT_ID: !Ref AgentId
          AGENT_ALIAS_ID: !Ref AgentAliasId
          # API_ENDPOINT: 
          #   Fn::ImportValue: !Sub 'sibyl-core-${Environment}-ApiEndpoint'
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MessageQueue.Arn
            BatchSize: 1  # Process one message at a time
            FunctionResponseTypes: ["ReportBatchItemFailures"]  # Enable partial batch processing
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sibyl/telegram/bot-token
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeAgent
            Resource:  !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent-alias/${AgentId}/${AgentAliasId}'
      Tags:
        Environment: !Ref Environment
        Application: SibylTelegram
    DependsOn: MessageProcessorLogGroup

  WebhookSetupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: sibyl_telegram_interface.handlers.webhook_setup.lambda_handler
      Description: Function to set up Telegram webhook
      LoggingConfig:
        LogGroup: !Ref WebhookSetupLogGroup
        LogFormat: Text
      Timeout: 60
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sibyl/telegram/bot-token
      Tags:
        Environment: !Ref Environment
        Application: SibylTelegram
    DependsOn: WebhookSetupLogGroup

  WebhookSetup:
    Type: Custom::WebhookSetup
    Properties:
      ServiceToken: !GetAtt WebhookSetupFunction.Arn
      FunctionUrl: !GetAtt WebhookHandlerFunctionUrl.FunctionUrl

Outputs:
  FunctionUrl:
    Description: "Lambda Function URL for the webhook"
    Value: !GetAtt WebhookHandlerFunctionUrl.FunctionUrl
  QueueUrl:
    Description: "URL of the SQS queue for message processing"
    Value: !Ref MessageQueue
  DLQUrl:
    Description: "URL of the Dead Letter Queue"
    Value: !Ref MessageQueueDLQ
